version: '3.8'

services:
  db:
    image: postgres:15
    container_name: padaria_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: padaria_royal
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgressql/data

volumes:
  pgdata: